### PR TITLE
Newcomers_Guide: missing space

### PR DESCRIPTION
**Pull request by charlesBak**
Put space before `difficulty/low`

Closes https://github.com/coala/documentation/issues/250

### CODE REVIEW

**Comment by underyx** [comment]
Hey @charlesBak, I'm afraid this commit message still isn't exactly as our guidelines require (you check them at coala.io/commit, by the way.)

Specifically what's not quite right is

> - [The shortlog] should describe the change
>   - Written in imperative present tense (i.e. Add something, not Adding something or Added something).

Your shortlog here is `Newcomers_Guide: missing space`, but it should be something like `Newcomers_Guide: Add missing space before 'difficulty/low'`, which you mistakenly wrote in the commit body instead. Once you've fixed this, I think we're good to go :)

**Comment by underyx** [comment]
Oh, whoops, I didn't realize I'm commenting on someone else's repo. Actually, I have even worse news than the above — the issue you fixed is actually already assigned to someone else, who opened a separate PR: https://github.com/coala/documentation/pull/258

**Comment by charlesBak** [comment]
@underyx  should i make an other PR for this issue?

**Comment by underyx** [comment]
@charlesBak no, if you have a look at http://docs.coala.io/en/latest/Developers/Newcomers_Guide.html you will see that this issue has already been fixed by someone else, actually. So, sorry, but I think your work went to waste here :(

I think you should comment on the issues that you're working on so this doesn't happen again.

**Comment by charlesBak** [comment]
thank you @underyx

**Pull request closed without merging**
